project_id = "qumrnazgdrijdcihtkah"

[functions.create-session]
verify_jwt = false

[functions.complete-session]
verify_jwt = false

[functions.import-shopify-products]
verify_jwt = false

[functions.import-woocommerce-products]
verify_jwt = false

[functions.upscale-design]
verify_jwt = false

[functions.detect-print-area]
verify_jwt = false